### ISSUE TITLE
addNewMBeansToSource write to file first then invoke loadSourceData()

### ISSUE THREAD

**Issue by pkhao75** [Su24-CS5004-Online-Lionelle/final-project-group-5#19]

**Comment by Stommasi19** [comment]
i thought we werent invoking loadsource data - we were going to write this.sourceList = the updated list after it is written to file

**Comment by pkhao75** [comment]
Yes, you're correct. The title was the issue we have, sorry I should've made it more clear. Issue fixed and closed
