### ISSUE TITLE
FilterOperation missing/wrong fields

### ISSUE THREAD

**Issue by tszwinglitw** [Su24-CS5004-Online-Lionelle/final-project-group-5#20]
- FilterOperation MPA Rating is not referring to the right field in the movie record
- FilterOperation/MovieData: Box Office Earnings is Missing from MovieData
- FilterOperation/MovieData: Writer is Missing from MovieData

**Comment by Stommasi19** [comment]
box office and writers were added into movieData, and into the filtering switch.
the the correct function call for the MPA rating replaced the old incorrect getter.
