### ISSUE TITLE
Delete Watchlist functionality missing

### ISSUE THREAD

**Issue by tszwinglitw** [Su24-CS5004-Online-Lionelle/final-project-group-5#21]

**Comment by pkhao75** [comment]
Delete functionality in Model created. Accept list ID for deletion and returns the same ID for completion or -1 for fail/error

**Comment by tszwinglitw** [comment]
Bound delete watchlist functionality to Controller in https://github.com/Su24-CS5004-Online-Lionelle/final-project-group-5/commit/49943829c8bfb253ff71b55a675107a30d0d860c
