### ISSUE TITLE
FilterOperation: Box Office Earnings Integer Overflow

### ISSUE THREAD

**Issue by tszwinglitw** [Su24-CS5004-Online-Lionelle/final-project-group-5#22]
Steps to reproduce:

- type 2147.5 in min/max field of the box office filters and apply 
- error occurs as this would overflow int32 signed integer value

**Comment by Stommasi19** [comment]
shouldnt we change the MBean to be a double then? then ill change the filter operation to be a double too?

**Comment by tszwinglitw** [comment]
or to maintain compatibility with the current components, you may want to clamp down the user input to the largest signed int32 as an error checking/user-input pre-processing measure - since no box office earning number is exceeding that range for now, it's just the user input
