### ISSUE TITLE
FilterPane rounding issue with Box Office Earnings

### ISSUE THREAD

**Issue by tszwinglitw** [Su24-CS5004-Online-Lionelle/final-project-group-5#23]
Current rounding mechanism for calculating suggested filter range would exclude current entries in the list.

Let:
- Entry 0: $674,292,608
- Entry 1: $15,205,725

In the current FilterPane rounding operation:
- $674,292,608 becomes $674,290,000
- $15,205,725 becomes $15,210,000
- Default range becomes: $15,210,000 to $674,290,000 - and both entries are excluded.

Suggested Solution: 
- Force round down for min-range
- Force round up for max-range

**Comment by jackeinbinder01** [comment]
Just pushed an update, pls confirm on your end
