### ISSUE TITLE
Deleted watchlists are reappearing after the app is restarted

### ISSUE THREAD

**Issue by jackeinbinder01** [Su24-CS5004-Online-Lionelle/final-project-group-5#26]

**Comment by pkhao75** [comment]
File.renameTo() was used initially to move deleted watchlist file from /watchlist to /unused but the method prevents overwriting existing file, causing the rename to fail and deleted watchlist stays inside the old folder.

Fix: Write deleted watchlist content down as a new file inside unused folder and use File.delete() to delete file inside watchlist folder
